# Generated by Django 3.2.22 on 2024-03-20 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20240320_1159'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UsersTasks',
        ),
    ]
