# Generated by Django 3.2.22 on 2024-03-27 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_delete_userstasks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='date_of_create',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='deadline',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='file',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='status',
            field=models.CharField(choices=[('Запланирована ', 'Запланирована'), ('В работе', 'В работе'), ('Выполнена', 'Выполнена'), ('Отменена', 'Отменена')], default='Запланирована', max_length=17),
        ),
    ]
