# Generated by Django 3.2.22 on 2024-08-06 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_auto_20240327_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='file',
            field=models.FileField(upload_to='documents/'),
        ),
    ]
