# Generated by Django 3.2.22 on 2024-03-20 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_tasks_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userstasks',
            name='task_id',
        ),
        migrations.RemoveField(
            model_name='userstasks',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='Tasks',
        ),
        migrations.DeleteModel(
            name='UsersTasks',
        ),
    ]
