# Generated by Django 3.2.22 on 2024-03-27 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_profiles_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Обычный'), (2, 'Премиум')], verbose_name='status'),
        ),
    ]
