# Generated by Django 3.2.22 on 2024-03-27 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_profiles_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='status',
            field=models.CharField(choices=[('Обычный', 'Обычный'), ('Премиум', 'Премиум')], max_length=7),
        ),
    ]
