# Generated by Django 3.2.22 on 2024-03-27 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_profiles_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='fk_user_profile',
            new_name='profile',
        ),
        migrations.AlterField(
            model_name='profiles',
            name='status',
            field=models.CharField(choices=[('Обычный', 'Обычный'), ('Премиум', 'Премиум')], default='Обычный', max_length=7),
        ),
    ]
