# Generated by Django 3.2.22 on 2024-03-29 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20240327_1305'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='profile',
            new_name='fk_user_profile',
        ),
    ]
