version: '3.8'

services:
  postgres:
    image: postgres:13.3
    restart: always
#    container_name: postgres

    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U root -d postgres" ]
      interval: 30s
      timeout: 15s
      retries: 5
      start_period: 10s
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G

  web:
    build:
      context: .
      dockerfile: Dockerfile
#    network_mode: host
    ports:
      - "8000:8000"
    depends_on:
      - postgres


