version: '3.8'

services:
  postgres:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: dbHw
    ports:
      - "5433:5432"

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U root -d dbHw" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G

  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:8000"
    depends_on:
      - postgres

