# Generated by Django 3.2.22 on 2024-03-20 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20240320_1159'),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserTasks',
            new_name='UsersTasks',
        ),
        migrations.AlterField(
            model_name='tasks',
            name='date_of_create',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='deadline',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='description',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='file',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='status',
            field=models.CharField(max_length=17),
        ),
    ]
