version: '3.8'

services:
  postgres:
    image: postgres:13.3
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: postgres

    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U root -d postgres" ]
      interval: 40s
      timeout: 15s
      retries: 5
      start_period: 30s
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G

#  rabbitmq:
#    image: rabbitmq:latest
#    restart: always
#    environment:
#      RABBITMQ_DEFAULT_USER: guest
#      RABBITMQ_DEFAULT_PASS: guest
#
#  redis:
#    image: redis:latest
#    restart: always

  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"

    depends_on:
      - postgres
#      - rabbitmq
#      - redis

