[tool.poetry]
name = "spaceoftanks"
version = "0.1.0"
description = ""
authors = ["Dmitry <dmitry.emelianenko@lyte.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
django = "3.2.22"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
